// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `open_db`, `storage_to_source_book_source`

/// Smoke test — 验证桥接是否正常工作
Future<String> ping() => RustLib.instance.api.crateApiPing();

/// 初始化函数 - 在 Flutter 应用启动时调用
Future<String> initLegado({required String dbPath}) =>
    RustLib.instance.api.crateApiInitLegado(dbPath: dbPath);

/// 获取数据库版本
Future<int> getDbVersion({required String dbPath}) =>
    RustLib.instance.api.crateApiGetDbVersion(dbPath: dbPath);

/// 获取书架上的所有书籍，返回 JSON 数组
Future<String> getAllBooks({required String dbPath}) =>
    RustLib.instance.api.crateApiGetAllBooks(dbPath: dbPath);

/// 搜索书架中的书籍，返回 JSON 数组
Future<String> searchBooksOffline(
        {required String dbPath, required String keyword}) =>
    RustLib.instance.api
        .crateApiSearchBooksOffline(dbPath: dbPath, keyword: keyword);

/// 保存一本书到书架（book_json 为 storage::Book 的 JSON）
Future<void> saveBook({required String dbPath, required String bookJson}) =>
    RustLib.instance.api.crateApiSaveBook(dbPath: dbPath, bookJson: bookJson);

/// 从书架删除一本书
Future<void> deleteBook({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteBook(dbPath: dbPath, id: id);

/// 获取所有书源，返回 JSON 数组
Future<String> getAllSources({required String dbPath}) =>
    RustLib.instance.api.crateApiGetAllSources(dbPath: dbPath);

/// 获取所有已启用的书源，返回 JSON 数组
Future<String> getEnabledSources({required String dbPath}) =>
    RustLib.instance.api.crateApiGetEnabledSources(dbPath: dbPath);

/// 保存书源（source_json 为 storage::BookSource 的 JSON）
Future<void> saveSource({required String dbPath, required String sourceJson}) =>
    RustLib.instance.api
        .crateApiSaveSource(dbPath: dbPath, sourceJson: sourceJson);

/// 便捷函数：仅需 name + url 即可创建书源（自动填充 id/enabled/timestamps 等必填字段）
Future<String> createSource(
        {required String dbPath, required String name, required String url}) =>
    RustLib.instance.api
        .crateApiCreateSource(dbPath: dbPath, name: name, url: url);

/// 删除书源
Future<void> deleteSource({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteSource(dbPath: dbPath, id: id);

/// 获取书源的原始 rule_search JSON（用于诊断），返回 JSON 或 null
Future<String> getSourceRuleSearchRaw(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api.crateApiGetSourceRuleSearchRaw(
        dbPath: dbPath, sourceId: sourceId);

// search_parse_html removed: that path was added under the false assumption
// of "Android DNS limitations". The on-device LegadoHttpClient handles cookies,
// charset, URL options, and JS templates that the Dart-side hand-rolled
// resolver did not. See git log for commit 3c25702 / the code-review report.

// TODO: Regenerate bridge code to restore deleteSourcesBatch
// /// 批量删除书源 (ids_json 为 JSON 字符串数组)
// Future<void> deleteSourcesBatch({required String dbPath, required String idsJson}) =>
//     RustLib.instance.api.crateApiDeleteSourcesBatch(dbPath: dbPath, idsJson: idsJson);

/// 批量删除书源 (ids_json 为 JSON 字符串数组)
/// Manually wired (codegen timeout, see CURRENT_STATUS.md FRB patch chapter)
Future<void> deleteSourcesBatch(
        {required String dbPath, required String idsJson}) =>
    RustLib.instance.api
        .crateApiDeleteSourcesBatch(dbPath: dbPath, idsJson: idsJson);

/// 获取书源的发现入口列表（返回 JSON 数组）
Future<String> getExploreEntries(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiGetExploreEntries(dbPath: dbPath, sourceId: sourceId);

/// 执行发现页请求，获取书籍列表（返回 JSON 数组）
Future<String> explore(
        {required String dbPath,
        required String sourceId,
        required String exploreUrl,
        required int page}) =>
    RustLib.instance.api.crateApiExplore(
        dbPath: dbPath,
        sourceId: sourceId,
        exploreUrl: exploreUrl,
        page: page);

/// 对内容应用所有已启用的替换规则。
///
/// 一次 FRB 调用替代之前 Dart 侧"拉规则 + 主 isolate 循环 RegExp"两步：
/// - 加载已启用规则用 [cacheGeneration] 参与的进程内缓存（Rust 侧 OnceLock）
/// - 编译失败的规则只 warn 一次
/// - 调用方在 ReplaceRule CRUD 后递增 [cacheGeneration] 即可让缓存失效
Future<String> applyReplaceRules(
        {required String dbPath,
        required String content,
        required PlatformInt64 cacheGeneration}) =>
    RustLib.instance.api.crateApiApplyReplaceRules(
        dbPath: dbPath,
        content: content,
        cacheGeneration: cacheGeneration);

/// 启用 / 禁用书源
Future<void> setSourceEnabled(
        {required String dbPath, required String id, required bool enabled}) =>
    RustLib.instance.api
        .crateApiSetSourceEnabled(dbPath: dbPath, id: id, enabled: enabled);

/// 从 JSON 批量导入书源
Future<int> importSourcesFromJson(
        {required String dbPath, required String json}) =>
    RustLib.instance.api
        .crateApiImportSourcesFromJson(dbPath: dbPath, json: json);

/// 获取书源（core_source::types::BookSource 格式），用于下载
Future<String> getSourceForDownload(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiGetSourceForDownload(dbPath: dbPath, sourceId: sourceId);

/// 获取某本书的所有章节，返回 JSON 数组
Future<String> getBookChapters(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetBookChapters(dbPath: dbPath, bookId: bookId);

/// 更新章节内容
Future<void> updateChapterContent(
        {required String dbPath,
        required String chapterId,
        required String content}) =>
    RustLib.instance.api.crateApiUpdateChapterContent(
        dbPath: dbPath, chapterId: chapterId, content: content);

/// 保存章节（chapter_json 为 storage::Chapter 的 JSON）
Future<void> saveChapter(
        {required String dbPath, required String chapterJson}) =>
    RustLib.instance.api
        .crateApiSaveChapter(dbPath: dbPath, chapterJson: chapterJson);

/// 批量替换某本书的章节（chapters_json 为 storage::Chapter 数组 JSON），保留相同 URL 的已缓存正文
Future<void> replaceBookChaptersPreservingContent(
        {required String dbPath,
        required String bookId,
        required String chaptersJson}) =>
    RustLib.instance.api.crateApiReplaceBookChaptersPreservingContent(
        dbPath: dbPath, bookId: bookId, chaptersJson: chaptersJson);

/// 批量替换某本书的章节（chapters_json 为 storage::Chapter 数组 JSON），不保留旧章节正文
Future<void> replaceBookChapters(
        {required String dbPath,
        required String bookId,
        required String chaptersJson}) =>
    RustLib.instance.api.crateApiReplaceBookChapters(
        dbPath: dbPath, bookId: bookId, chaptersJson: chaptersJson);

/// 删除章节
Future<void> deleteChapter({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteChapter(dbPath: dbPath, id: id);

/// 保存阅读进度
Future<void> saveReadingProgress(
        {required String dbPath,
        required String bookId,
        required int chapterIndex,
        required int paragraphIndex,
        required int offset}) =>
    RustLib.instance.api.crateApiSaveReadingProgress(
        dbPath: dbPath,
        bookId: bookId,
        chapterIndex: chapterIndex,
        paragraphIndex: paragraphIndex,
        offset: offset);

/// 获取阅读进度，返回 JSON 或 null
Future<String> getReadingProgress(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetReadingProgress(dbPath: dbPath, bookId: bookId);

/// 获取某本书的所有书签，返回 JSON 数组
Future<String> getBookmarks({required String dbPath, required String bookId}) =>
    RustLib.instance.api.crateApiGetBookmarks(dbPath: dbPath, bookId: bookId);

/// 添加书签，返回新书签的 JSON
Future<String> addBookmark(
        {required String dbPath,
        required String bookId,
        required int chapterIndex,
        required int paragraphIndex,
        String? content}) =>
    RustLib.instance.api.crateApiAddBookmark(
        dbPath: dbPath,
        bookId: bookId,
        chapterIndex: chapterIndex,
        paragraphIndex: paragraphIndex,
        content: content);

/// 删除书签
Future<void> deleteBookmark(
        {required String dbPath, required String bookmarkId}) =>
    RustLib.instance.api
        .crateApiDeleteBookmark(dbPath: dbPath, bookmarkId: bookmarkId);

/// 搜索在线书籍（source_json 为 core_source::BookSource 的 JSON），返回搜索结果 JSON 数组
Future<String> searchBooksOnline(
        {required String sourceJson, required String keyword}) =>
    RustLib.instance.api
        .crateApiSearchBooksOnline(sourceJson: sourceJson, keyword: keyword);

/// 获取在线书籍详情，返回 JSON 或 null
Future<String> getBookInfoOnline(
        {required String sourceJson, required String bookUrl}) =>
    RustLib.instance.api
        .crateApiGetBookInfoOnline(sourceJson: sourceJson, bookUrl: bookUrl);

/// 获取在线章节列表，返回 JSON 数组
Future<String> getChapterListOnline(
        {required String sourceJson, required String bookUrl}) =>
    RustLib.instance.api
        .crateApiGetChapterListOnline(sourceJson: sourceJson, bookUrl: bookUrl);

/// 获取在线章节内容，返回 JSON 或 null
Future<String> getChapterContentOnline(
        {required String sourceJson, required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentOnline(
        sourceJson: sourceJson, chapterUrl: chapterUrl);

/// 从数据库加载书源并搜索（异步），返回搜索结果 JSON 数组
Future<String> searchWithSourceFromDb(
        {required String dbPath,
        required String sourceId,
        required String keyword}) =>
    RustLib.instance.api.crateApiSearchWithSourceFromDb(
        dbPath: dbPath, sourceId: sourceId, keyword: keyword);

/// 从数据库加载书源并搜索 v2（异步），返回带错误信息的包装结果
Future<String> searchWithSourceFromDbV2(
        {required String dbPath,
        required String sourceId,
        required String keyword}) =>
    RustLib.instance.api.crateApiSearchWithSourceFromDbV2(
        dbPath: dbPath, sourceId: sourceId, keyword: keyword);

/// 从数据库加载书源并获取章节内容（异步），返回 JSON 或 null
Future<String> getChapterContentWithSourceFromDb(
        {required String dbPath,
        required String sourceId,
        required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentWithSourceFromDb(
        dbPath: dbPath, sourceId: sourceId, chapterUrl: chapterUrl);

/// 获取所有下载任务，返回 JSON 数组
Future<String> getDownloadTasks({required String dbPath}) =>
    RustLib.instance.api.crateApiGetDownloadTasks(dbPath: dbPath);

/// 根据书籍 ID 获取下载任务
Future<String> getDownloadTaskByBook(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetDownloadTaskByBook(dbPath: dbPath, bookId: bookId);

/// 创建下载任务（task_json 为 DownloadTask 的 JSON），返回 JSON
Future<String> createDownloadTask(
        {required String dbPath, required String taskJson}) =>
    RustLib.instance.api
        .crateApiCreateDownloadTask(dbPath: dbPath, taskJson: taskJson);

/// 事务性创建下载任务和章节
Future<String> createDownloadTaskWithChapters(
        {required String dbPath,
        required String taskJson,
        required String chaptersJson}) =>
    RustLib.instance.api.crateApiCreateDownloadTaskWithChapters(
        dbPath: dbPath, taskJson: taskJson, chaptersJson: chaptersJson);

/// 更新下载任务状态
Future<void> updateDownloadTaskStatus(
        {required String dbPath,
        required String taskId,
        required int status,
        String? errorMessage}) =>
    RustLib.instance.api.crateApiUpdateDownloadTaskStatus(
        dbPath: dbPath,
        taskId: taskId,
        status: status,
        errorMessage: errorMessage);

/// 更新下载进度
Future<void> updateDownloadProgress(
        {required String dbPath,
        required String taskId,
        required int downloadedChapters,
        required PlatformInt64 downloadedSize}) =>
    RustLib.instance.api.crateApiUpdateDownloadProgress(
        dbPath: dbPath,
        taskId: taskId,
        downloadedChapters: downloadedChapters,
        downloadedSize: downloadedSize);

/// 删除下载任务（同时清理已下载的文件）
Future<void> deleteDownloadTask(
        {required String dbPath, required String taskId}) =>
    RustLib.instance.api
        .crateApiDeleteDownloadTask(dbPath: dbPath, taskId: taskId);

/// 获取下载章节列表，返回 JSON 数组
Future<String> getDownloadChapters(
        {required String dbPath, required String taskId}) =>
    RustLib.instance.api
        .crateApiGetDownloadChapters(dbPath: dbPath, taskId: taskId);

/// 批量创建下载章节记录
Future<void> batchCreateDownloadChapters(
        {required String dbPath, required String chaptersJson}) =>
    RustLib.instance.api.crateApiBatchCreateDownloadChapters(
        dbPath: dbPath, chaptersJson: chaptersJson);

/// 更新下载章节状态
Future<void> updateDownloadChapterStatus(
        {required String dbPath,
        required String chapterId,
        required int status,
        String? filePath,
        required PlatformInt64 fileSize,
        String? errorMessage}) =>
    RustLib.instance.api.crateApiUpdateDownloadChapterStatus(
        dbPath: dbPath,
        chapterId: chapterId,
        status: status,
        filePath: filePath,
        fileSize: fileSize,
        errorMessage: errorMessage);

/// 下载并保存单个章节到本地文件，更新数据库状态
Future<String> downloadAndSaveChapter(
        {required String dbPath,
        required String taskId,
        required String downloadChapterId,
        required String sourceJson,
        required String chapterUrl,
        required String downloadDir}) =>
    RustLib.instance.api.crateApiDownloadAndSaveChapter(
        dbPath: dbPath,
        taskId: taskId,
        downloadChapterId: downloadChapterId,
        sourceJson: sourceJson,
        chapterUrl: chapterUrl,
        downloadDir: downloadDir);

/// 验证书源规则（source_json 为 core_source::types::BookSource 的 JSON），返回 JSON 数组
Future<String> validateSourceRules({required String sourceJson}) =>
    RustLib.instance.api.crateApiValidateSourceRules(sourceJson: sourceJson);

/// 验证数据库中的书源规则，返回 JSON 数组 [{field, severity, message}]
Future<String> validateSourceFromDb(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiValidateSourceFromDb(dbPath: dbPath, sourceId: sourceId);

/// 导出所有书源为 JSON 数组
Future<String> exportAllSources({required String dbPath}) =>
    RustLib.instance.api.crateApiExportAllSources(dbPath: dbPath);

/// 获取所有替换规则，返回 JSON 数组
Future<String> getReplaceRules({required String dbPath}) =>
    RustLib.instance.api.crateApiGetReplaceRules(dbPath: dbPath);

/// 保存替换规则（ruleJson 为 ReplaceRule 的 JSON），upsert 语义
Future<void> saveReplaceRule(
        {required String dbPath, required String ruleJson}) =>
    RustLib.instance.api
        .crateApiSaveReplaceRule(dbPath: dbPath, ruleJson: ruleJson);

/// 删除替换规则
Future<void> deleteReplaceRule({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteReplaceRule(dbPath: dbPath, id: id);

/// 启用 / 禁用替换规则
Future<void> setReplaceRuleEnabled(
        {required String dbPath, required String id, required bool enabled}) =>
    RustLib.instance.api.crateApiSetReplaceRuleEnabled(
        dbPath: dbPath, id: id, enabled: enabled);
