// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_replace_rules_impl`, `block_on_explore`, `ensure_regex_generation`, `get_or_compile_regex`, `get_or_load_rules`, `matches_scope`, `new`, `open_db`, `recompute_download_task_status`, `resolve_download_root`, `safe_download_file_name`, `storage_to_source_book_source`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ReplaceRulesCache`

/// Smoke test — 验证桥接是否正常工作
Future<String> ping() => RustLib.instance.api.crateApiPing();

/// 初始化函数 - 在 Flutter 应用启动时调用
Future<String> initLegado({required String dbPath}) =>
    RustLib.instance.api.crateApiInitLegado(dbPath: dbPath);

/// 获取数据库版本
Future<int> getDbVersion({required String dbPath}) =>
    RustLib.instance.api.crateApiGetDbVersion(dbPath: dbPath);

/// 获取书架上的所有书籍，返回 JSON 数组。
///
/// 批次 8 (2026-05): 加 `sort_order: i32` 参数（0=Default/1=Name/2=Author/
/// 3=TimeAdd/4=DurTime/5=ChapterCount，越界回 Default）。语义详见
/// [`core_storage::book_dao::BookSort::from_i32`]。Flutter 端 `bookshelfSort`
/// 设置直接透传过来。
Future<String> getAllBooks(
        {required String dbPath, required int sortOrder}) =>
    RustLib.instance.api
        .crateApiGetAllBooks(dbPath: dbPath, sortOrder: sortOrder);

/// 搜索书架中的书籍，返回 JSON 数组
Future<String> searchBooksOffline(
        {required String dbPath, required String keyword}) =>
    RustLib.instance.api
        .crateApiSearchBooksOffline(dbPath: dbPath, keyword: keyword);

/// 保存一本书到书架（book_json 为 storage::Book 的 JSON）
Future<void> saveBook({required String dbPath, required String bookJson}) =>
    RustLib.instance.api.crateApiSaveBook(dbPath: dbPath, bookJson: bookJson);

/// 从书架删除一本书（同时级联删除该书籍的章节和阅读进度）
Future<void> deleteBook({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteBook(dbPath: dbPath, id: id);

/// 列出所有书架分组（按 sort_order 升序），返回 JSON 数组
Future<String> listBookGroups({required String dbPath}) =>
    RustLib.instance.api.crateApiListBookGroups(dbPath: dbPath);

/// 创建新分组，返回新分组的 JSON
Future<String> createBookGroup(
        {required String dbPath,
        required String name,
        required int sortOrder}) =>
    RustLib.instance.api.crateApiCreateBookGroup(
        dbPath: dbPath, name: name, sortOrder: sortOrder);

/// 更新分组的 name + sort_order
Future<void> updateBookGroup(
        {required String dbPath,
        required PlatformInt64 id,
        required String name,
        required int sortOrder}) =>
    RustLib.instance.api.crateApiUpdateBookGroup(
        dbPath: dbPath, id: id, name: name, sortOrder: sortOrder);

/// 删除分组（同事务把组内书的 group_id 重置为 0）
Future<void> deleteBookGroup(
        {required String dbPath, required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDeleteBookGroup(dbPath: dbPath, id: id);

/// 列出某分组下的书籍。
///
/// `group_id` 语义：
/// - `-1` → 全部（等价 [`get_all_books`]）
/// - `0`  → 未分组
/// - `>= 1` → 具体某个分组
///
/// 批次 8 (2026-05): 加 `sort_order: i32`，与 [`get_all_books`] 同语义。
Future<String> listBooksByGroup(
        {required String dbPath,
        required PlatformInt64 groupId,
        required int sortOrder}) =>
    RustLib.instance.api.crateApiListBooksByGroup(
        dbPath: dbPath, groupId: groupId, sortOrder: sortOrder);

/// 把一本书移动到指定分组（`group_id = 0` 表示移回"未分组"）
Future<void> setBookGroup(
        {required String dbPath,
        required String bookId,
        required PlatformInt64 groupId}) =>
    RustLib.instance.api
        .crateApiSetBookGroup(dbPath: dbPath, bookId: bookId, groupId: groupId);

/// 获取所有书源，返回 JSON 数组
Future<String> getAllSources({required String dbPath}) =>
    RustLib.instance.api.crateApiGetAllSources(dbPath: dbPath);

/// 获取所有已启用的书源，返回 JSON 数组
Future<String> getEnabledSources({required String dbPath}) =>
    RustLib.instance.api.crateApiGetEnabledSources(dbPath: dbPath);

/// 保存书源（source_json 为 storage::BookSource 的 JSON）
Future<void> saveSource({required String dbPath, required String sourceJson}) =>
    RustLib.instance.api
        .crateApiSaveSource(dbPath: dbPath, sourceJson: sourceJson);

/// 便捷函数：仅需 name + url 即可创建书源（自动填充 id/enabled/timestamps 等必填字段）
Future<String> createSource(
        {required String dbPath, required String name, required String url}) =>
    RustLib.instance.api
        .crateApiCreateSource(dbPath: dbPath, name: name, url: url);

/// 删除书源
Future<void> deleteSource({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteSource(dbPath: dbPath, id: id);

/// 批量删除书源 (ids_json 为 JSON 字符串数组)
Future<void> deleteSourcesBatch(
        {required String dbPath, required String idsJson}) =>
    RustLib.instance.api
        .crateApiDeleteSourcesBatch(dbPath: dbPath, idsJson: idsJson);

/// 启用 / 禁用书源
Future<void> setSourceEnabled(
        {required String dbPath, required String id, required bool enabled}) =>
    RustLib.instance.api
        .crateApiSetSourceEnabled(dbPath: dbPath, id: id, enabled: enabled);

/// 从 JSON 批量导入书源
Future<int> importSourcesFromJson(
        {required String dbPath, required String json}) =>
    RustLib.instance.api
        .crateApiImportSourcesFromJson(dbPath: dbPath, json: json);

/// 获取书源（core_source::types::BookSource 格式），用于下载
Future<String> getSourceForDownload(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiGetSourceForDownload(dbPath: dbPath, sourceId: sourceId);

/// 获取某本书的所有章节，返回 JSON 数组
Future<String> getBookChapters(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetBookChapters(dbPath: dbPath, bookId: bookId);

/// 更新章节内容
Future<void> updateChapterContent(
        {required String dbPath,
        required String chapterId,
        required String content}) =>
    RustLib.instance.api.crateApiUpdateChapterContent(
        dbPath: dbPath, chapterId: chapterId, content: content);

/// 保存章节（chapter_json 为 storage::Chapter 的 JSON）
Future<void> saveChapter(
        {required String dbPath, required String chapterJson}) =>
    RustLib.instance.api
        .crateApiSaveChapter(dbPath: dbPath, chapterJson: chapterJson);

/// 批量替换某本书的章节（chapters_json 为 storage::Chapter 数组 JSON），保留相同 URL 的已缓存正文
Future<void> replaceBookChaptersPreservingContent(
        {required String dbPath,
        required String bookId,
        required String chaptersJson}) =>
    RustLib.instance.api.crateApiReplaceBookChaptersPreservingContent(
        dbPath: dbPath, bookId: bookId, chaptersJson: chaptersJson);

/// 批量替换某本书的章节（chapters_json 为 storage::Chapter 数组 JSON），不保留旧章节正文
Future<void> replaceBookChapters(
        {required String dbPath,
        required String bookId,
        required String chaptersJson}) =>
    RustLib.instance.api.crateApiReplaceBookChapters(
        dbPath: dbPath, bookId: bookId, chaptersJson: chaptersJson);

/// 删除章节
Future<void> deleteChapter({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteChapter(dbPath: dbPath, id: id);

/// 保存阅读进度
Future<void> saveReadingProgress(
        {required String dbPath,
        required String bookId,
        required int chapterIndex,
        required int paragraphIndex,
        required int offset}) =>
    RustLib.instance.api.crateApiSaveReadingProgress(
        dbPath: dbPath,
        bookId: bookId,
        chapterIndex: chapterIndex,
        paragraphIndex: paragraphIndex,
        offset: offset);

/// 获取阅读进度，返回 JSON 或 null
Future<String> getReadingProgress(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetReadingProgress(dbPath: dbPath, bookId: bookId);

/// 获取某本书的所有书签，返回 JSON 数组
Future<String> getBookmarks({required String dbPath, required String bookId}) =>
    RustLib.instance.api.crateApiGetBookmarks(dbPath: dbPath, bookId: bookId);

/// 添加书签，返回新书签的 JSON
Future<String> addBookmark(
        {required String dbPath,
        required String bookId,
        required int chapterIndex,
        required int paragraphIndex,
        String? content}) =>
    RustLib.instance.api.crateApiAddBookmark(
        dbPath: dbPath,
        bookId: bookId,
        chapterIndex: chapterIndex,
        paragraphIndex: paragraphIndex,
        content: content);

/// 删除书签
Future<void> deleteBookmark(
        {required String dbPath, required String bookmarkId}) =>
    RustLib.instance.api
        .crateApiDeleteBookmark(dbPath: dbPath, bookmarkId: bookmarkId);

/// 搜索在线书籍（source_json 为 core_source::BookSource 的 JSON），返回搜索结果 JSON 数组
///
/// R82: 区分 ParserError::Empty（成功 0 结果，返回 `[]`）与其他失败（Network /
/// RuleConfig / Parse，作为 Err(String) 返回让 Dart 侧能 toast 出来）。
Future<String> searchBooksOnline(
        {required String sourceJson, required String keyword}) =>
    RustLib.instance.api
        .crateApiSearchBooksOnline(sourceJson: sourceJson, keyword: keyword);

/// 获取在线书籍详情，返回 JSON 或 null
Future<String> getBookInfoOnline(
        {required String sourceJson, required String bookUrl}) =>
    RustLib.instance.api
        .crateApiGetBookInfoOnline(sourceJson: sourceJson, bookUrl: bookUrl);

/// 获取在线章节列表，返回 JSON 数组
Future<String> getChapterListOnline(
        {required String sourceJson, required String bookUrl}) =>
    RustLib.instance.api
        .crateApiGetChapterListOnline(sourceJson: sourceJson, bookUrl: bookUrl);

/// 获取在线章节内容，返回 JSON 或 null
Future<String> getChapterContentOnline(
        {required String sourceJson, required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentOnline(
        sourceJson: sourceJson, chapterUrl: chapterUrl);

/// 获取书源的原始 rule_search JSON（用于诊断），返回 JSON 或 null
Future<String> getSourceRuleSearchRaw(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiGetSourceRuleSearchRaw(dbPath: dbPath, sourceId: sourceId);

/// 从数据库加载书源并搜索（异步），返回搜索结果 JSON 数组
/// 包装结果：正常时返回 [{"ok":true,"data":[...]}]，失败时返回 [{"ok":false,"error":"..."}]
Future<String> searchWithSourceFromDbV2(
        {required String dbPath,
        required String sourceId,
        required String keyword}) =>
    RustLib.instance.api.crateApiSearchWithSourceFromDbV2(
        dbPath: dbPath, sourceId: sourceId, keyword: keyword);

/// 从数据库加载书源并搜索（异步），返回搜索结果 JSON 数组
Future<String> searchWithSourceFromDb(
        {required String dbPath,
        required String sourceId,
        required String keyword}) =>
    RustLib.instance.api.crateApiSearchWithSourceFromDb(
        dbPath: dbPath, sourceId: sourceId, keyword: keyword);

/// 从数据库加载书源并获取章节内容（异步），返回 JSON 或 null
Future<String> getChapterContentWithSourceFromDb(
        {required String dbPath,
        required String sourceId,
        required String chapterUrl}) =>
    RustLib.instance.api.crateApiGetChapterContentWithSourceFromDb(
        dbPath: dbPath, sourceId: sourceId, chapterUrl: chapterUrl);

/// 获取所有下载任务，返回 JSON 数组
Future<String> getDownloadTasks({required String dbPath}) =>
    RustLib.instance.api.crateApiGetDownloadTasks(dbPath: dbPath);

/// 根据书籍 ID 获取下载任务
Future<String> getDownloadTaskByBook(
        {required String dbPath, required String bookId}) =>
    RustLib.instance.api
        .crateApiGetDownloadTaskByBook(dbPath: dbPath, bookId: bookId);

/// 创建下载任务（task_json 为 DownloadTask 的 JSON），返回 JSON
Future<String> createDownloadTask(
        {required String dbPath, required String taskJson}) =>
    RustLib.instance.api
        .crateApiCreateDownloadTask(dbPath: dbPath, taskJson: taskJson);

/// 事务性创建下载任务和章节
Future<String> createDownloadTaskWithChapters(
        {required String dbPath,
        required String taskJson,
        required String chaptersJson}) =>
    RustLib.instance.api.crateApiCreateDownloadTaskWithChapters(
        dbPath: dbPath, taskJson: taskJson, chaptersJson: chaptersJson);

/// 更新下载任务状态
Future<void> updateDownloadTaskStatus(
        {required String dbPath,
        required String taskId,
        required int status,
        String? errorMessage}) =>
    RustLib.instance.api.crateApiUpdateDownloadTaskStatus(
        dbPath: dbPath,
        taskId: taskId,
        status: status,
        errorMessage: errorMessage);

/// 更新下载进度
Future<void> updateDownloadProgress(
        {required String dbPath,
        required String taskId,
        required int downloadedChapters,
        required PlatformInt64 downloadedSize}) =>
    RustLib.instance.api.crateApiUpdateDownloadProgress(
        dbPath: dbPath,
        taskId: taskId,
        downloadedChapters: downloadedChapters,
        downloadedSize: downloadedSize);

/// 删除下载任务（同时清理已下载的文件）
Future<void> deleteDownloadTask(
        {required String dbPath, required String taskId}) =>
    RustLib.instance.api
        .crateApiDeleteDownloadTask(dbPath: dbPath, taskId: taskId);

/// 获取下载章节列表，返回 JSON 数组
Future<String> getDownloadChapters(
        {required String dbPath, required String taskId}) =>
    RustLib.instance.api
        .crateApiGetDownloadChapters(dbPath: dbPath, taskId: taskId);

/// 批量创建下载章节记录
Future<void> batchCreateDownloadChapters(
        {required String dbPath, required String chaptersJson}) =>
    RustLib.instance.api.crateApiBatchCreateDownloadChapters(
        dbPath: dbPath, chaptersJson: chaptersJson);

/// 更新下载章节状态
Future<void> updateDownloadChapterStatus(
        {required String dbPath,
        required String chapterId,
        required int status,
        String? filePath,
        required PlatformInt64 fileSize,
        String? errorMessage}) =>
    RustLib.instance.api.crateApiUpdateDownloadChapterStatus(
        dbPath: dbPath,
        chapterId: chapterId,
        status: status,
        filePath: filePath,
        fileSize: fileSize,
        errorMessage: errorMessage);

/// 下载并保存单个章节到本地文件，更新数据库状态
Future<String> downloadAndSaveChapter(
        {required String dbPath,
        required String taskId,
        required String downloadChapterId,
        required String sourceJson,
        required String chapterUrl,
        required String downloadDir}) =>
    RustLib.instance.api.crateApiDownloadAndSaveChapter(
        dbPath: dbPath,
        taskId: taskId,
        downloadChapterId: downloadChapterId,
        sourceJson: sourceJson,
        chapterUrl: chapterUrl,
        downloadDir: downloadDir);

/// 验证书源规则（source_json 为 core_source::types::BookSource 的 JSON），返回 JSON 数组
Future<String> validateSourceRules({required String sourceJson}) =>
    RustLib.instance.api.crateApiValidateSourceRules(sourceJson: sourceJson);

/// 验证数据库中的书源规则，返回 JSON 数组 [{field, severity, message}]
Future<String> validateSourceFromDb(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiValidateSourceFromDb(dbPath: dbPath, sourceId: sourceId);

/// 导出所有书源为 Legado 兼容 JSON 数组（camelCase 格式）
Future<String> exportAllSources({required String dbPath}) =>
    RustLib.instance.api.crateApiExportAllSources(dbPath: dbPath);

/// 获取书源的发现入口列表
Future<String> getExploreEntries(
        {required String dbPath, required String sourceId}) =>
    RustLib.instance.api
        .crateApiGetExploreEntries(dbPath: dbPath, sourceId: sourceId);

/// 执行发现页请求，获取书籍列表
Future<String> explore(
        {required String dbPath,
        required String sourceId,
        required String exploreUrl,
        required int page}) =>
    RustLib.instance.api.crateApiExplore(
        dbPath: dbPath, sourceId: sourceId, exploreUrl: exploreUrl, page: page);

/// 获取所有替换规则，返回 JSON 数组
Future<String> getReplaceRules({required String dbPath}) =>
    RustLib.instance.api.crateApiGetReplaceRules(dbPath: dbPath);

/// 保存替换规则（rule_json 为 storage::ReplaceRule 的 JSON），upsert 语义
Future<void> saveReplaceRule(
        {required String dbPath, required String ruleJson}) =>
    RustLib.instance.api
        .crateApiSaveReplaceRule(dbPath: dbPath, ruleJson: ruleJson);

/// 删除替换规则
Future<void> deleteReplaceRule({required String dbPath, required String id}) =>
    RustLib.instance.api.crateApiDeleteReplaceRule(dbPath: dbPath, id: id);

/// 启用 / 禁用替换规则
Future<void> setReplaceRuleEnabled(
        {required String dbPath, required String id, required bool enabled}) =>
    RustLib.instance.api.crateApiSetReplaceRuleEnabled(
        dbPath: dbPath, id: id, enabled: enabled);

/// 对内容应用所有已启用的替换规则。
///
/// 这是 P1-7 的修复：之前 Dart 端在每次切章节时通过 FRB 拉一次规则列表，
/// 然后在主 isolate 里循环 `RegExp(...).replaceAll`，长正文 + 多条规则会
/// 阻塞 UI。现在统一下沉到 Rust 单次调用：
///
///   - 编译失败的规则只 warn 一次（避免每章都 spam 日志）
///   - 整个循环在 Rust 端跑，不占 Dart 主 isolate
///   - 调用方只需把 db_path + 原始内容传过来
///
/// 同时 Dart 侧的 ReplaceRule 缓存也可以复用：参数加 `cache_generation`，
/// Rust 端用 OnceLock + RwLock 保存上次拉取的规则；调用方在 ReplaceRule
/// CRUD 后递增 generation 即可让缓存失效，不必每次走 DAO。
///
/// **R24**: scope 现在按 Legado 原版语义匹配。`book_name` 与
/// `book_origin` 由 caller 提供（reader_page 持有），filter 逻辑见
/// [`matches_scope`]。`apply_to_title=true` 表示本次跑作用于标题
/// 的规则；false 表示作用于正文。
Future<String> applyReplaceRules(
        {required String dbPath,
        required String content,
        required PlatformInt64 cacheGeneration,
        String? bookName,
        String? bookOrigin,
        required bool applyToTitle}) =>
    RustLib.instance.api.crateApiApplyReplaceRules(
        dbPath: dbPath,
        content: content,
        cacheGeneration: cacheGeneration,
        bookName: bookName,
        bookOrigin: bookOrigin,
        applyToTitle: applyToTitle);

// ============================================================
// 本地备份 / 恢复（批次 10）
// ============================================================

/// 把当前 DB 5 张表（books / book_groups / bookmarks / replace_rules /
/// book_sources）导出成 Legado 兼容的 zip 备份。
Future<void> exportBackupZip(
        {required String dbPath, required String outZipPath}) =>
    RustLib.instance.api
        .crateApiExportBackupZip(dbPath: dbPath, outZipPath: outZipPath);

/// 解压 zip → 字段映射 → upsert 入库。返回 `ImportSummary` 的 JSON 字符串
/// （`{books, groups, bookmarks, replace_rules, sources, errors}`）。
Future<String> importBackupZip(
        {required String dbPath, required String zipPath}) =>
    RustLib.instance.api
        .crateApiImportBackupZip(dbPath: dbPath, zipPath: zipPath);

/// 列 zip 内**已识别**的 Legado 备份文件名（不解析内容，dry-run 用）。
/// 返回 JSON 字符串数组。
Future<String> validateBackupZip({required String zipPath}) =>
    RustLib.instance.api.crateApiValidateBackupZip(zipPath: zipPath);

// ============================================================
// WebDAV 同步（批次 11）
// ============================================================

/// 探活 — 验证 WebDAV URL + 凭据。失败抛 String 错误。
Future<void> webdavCheck(
        {required String url,
        required String user,
        required String password}) =>
    RustLib.instance.api
        .crateApiWebdavCheck(url: url, user: user, password: password);

/// 列远端 base_url 下的 backup*.zip 文件名。返回 JSON 字符串数组。
Future<String> webdavListBackups(
        {required String url,
        required String user,
        required String password}) =>
    RustLib.instance.api
        .crateApiWebdavListBackups(url: url, user: user, password: password);

/// 本地 export → 临时 zip → PUT 到 WebDAV。
Future<void> webdavUploadBackup(
        {required String dbPath,
        required String url,
        required String user,
        required String password,
        required String fileName}) =>
    RustLib.instance.api.crateApiWebdavUploadBackup(
        dbPath: dbPath,
        url: url,
        user: user,
        password: password,
        fileName: fileName);

/// GET 远端 zip → 写到临时文件 → import → 返回 ImportSummary JSON。
Future<String> webdavDownloadBackup(
        {required String dbPath,
        required String url,
        required String user,
        required String password,
        required String fileName}) =>
    RustLib.instance.api.crateApiWebdavDownloadBackup(
        dbPath: dbPath,
        url: url,
        user: user,
        password: password,
        fileName: fileName);

/// 删除远端 backup zip。
Future<void> webdavDeleteBackup(
        {required String url,
        required String user,
        required String password,
        required String fileName}) =>
    RustLib.instance.api.crateApiWebdavDeleteBackup(
        url: url, user: user, password: password, fileName: fileName);
