// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -916733173;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'bridge',
    ioDirectory: '../core/bridge/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAddBookmark(
      {required String dbPath,
      required String bookId,
      required int chapterIndex,
      required int paragraphIndex,
      String? content});

  Future<void> crateApiBatchCreateDownloadChapters(
      {required String dbPath, required String chaptersJson});

  Future<String> crateApiCreateDownloadTask(
      {required String dbPath, required String taskJson});

  Future<String> crateApiCreateDownloadTaskWithChapters(
      {required String dbPath,
      required String taskJson,
      required String chaptersJson});

  Future<String> crateApiCreateSource(
      {required String dbPath, required String name, required String url});

  Future<void> crateApiDeleteBook({required String dbPath, required String id});

  Future<void> crateApiDeleteBookmark(
      {required String dbPath, required String bookmarkId});

  Future<void> crateApiDeleteChapter(
      {required String dbPath, required String id});

  Future<void> crateApiDeleteDownloadTask(
      {required String dbPath, required String taskId});

  Future<void> crateApiDeleteSource(
      {required String dbPath, required String id});

  Future<String> crateApiDownloadAndSaveChapter(
      {required String dbPath,
      required String taskId,
      required String downloadChapterId,
      required String sourceJson,
      required String chapterUrl,
      required String downloadDir});

  Future<String> crateApiGetAllBooks({required String dbPath});

  Future<String> crateApiGetAllSources({required String dbPath});

  Future<String> crateApiGetBookChapters(
      {required String dbPath, required String bookId});

  Future<String> crateApiGetBookInfoOnline(
      {required String sourceJson, required String bookUrl});

  Future<String> crateApiGetBookmarks(
      {required String dbPath, required String bookId});

  Future<String> crateApiGetChapterContentOnline(
      {required String sourceJson, required String chapterUrl});

  Future<String> crateApiGetChapterContentWithSourceFromDb(
      {required String dbPath,
      required String sourceId,
      required String chapterUrl});

  Future<String> crateApiGetChapterListOnline(
      {required String sourceJson, required String bookUrl});

  Future<int> crateApiGetDbVersion({required String dbPath});

  Future<String> crateApiGetDownloadChapters(
      {required String dbPath, required String taskId});

  Future<String> crateApiGetDownloadTaskByBook(
      {required String dbPath, required String bookId});

  Future<String> crateApiGetDownloadTasks({required String dbPath});

  Future<String> crateApiGetEnabledSources({required String dbPath});

  Future<String> crateApiGetReadingProgress(
      {required String dbPath, required String bookId});

  Future<String> crateApiGetSourceForDownload(
      {required String dbPath, required String sourceId});

  Future<int> crateApiImportSourcesFromJson(
      {required String dbPath, required String json});

  Future<String> crateApiInitLegado({required String dbPath});

  Future<String> crateApiPing();

  Future<void> crateApiReplaceBookChapters(
      {required String dbPath,
      required String bookId,
      required String chaptersJson});

  Future<void> crateApiReplaceBookChaptersPreservingContent(
      {required String dbPath,
      required String bookId,
      required String chaptersJson});

  Future<void> crateApiSaveBook(
      {required String dbPath, required String bookJson});

  Future<void> crateApiSaveChapter(
      {required String dbPath, required String chapterJson});

  Future<void> crateApiSaveReadingProgress(
      {required String dbPath,
      required String bookId,
      required int chapterIndex,
      required int paragraphIndex,
      required int offset});

  Future<void> crateApiSaveSource(
      {required String dbPath, required String sourceJson});

  Future<String> crateApiSearchBooksOffline(
      {required String dbPath, required String keyword});

  Future<String> crateApiSearchBooksOnline(
      {required String sourceJson, required String keyword});

  Future<String> crateApiSearchWithSourceFromDb(
      {required String dbPath,
      required String sourceId,
      required String keyword});

  Future<String> crateApiSearchWithSourceFromDbV2(
      {required String dbPath,
      required String sourceId,
      required String keyword});

  Future<void> crateApiSetSourceEnabled(
      {required String dbPath, required String id, required bool enabled});

  Future<void> crateApiUpdateChapterContent(
      {required String dbPath,
      required String chapterId,
      required String content});

  Future<void> crateApiUpdateDownloadChapterStatus(
      {required String dbPath,
      required String chapterId,
      required int status,
      String? filePath,
      required PlatformInt64 fileSize,
      String? errorMessage});

  Future<void> crateApiUpdateDownloadProgress(
      {required String dbPath,
      required String taskId,
      required int downloadedChapters,
      required PlatformInt64 downloadedSize});

  Future<void> crateApiUpdateDownloadTaskStatus(
      {required String dbPath,
      required String taskId,
      required int status,
      String? errorMessage});

  Future<String> crateApiValidateSourceRules({required String sourceJson});

  Future<String> crateApiValidateSourceFromDb(
      {required String dbPath, required String sourceId});

  Future<String> crateApiExportAllSources({required String dbPath});

  Future<String> crateApiGetReplaceRules({required String dbPath});

  Future<String> crateApiGetSourceRuleSearchRaw(
      {required String dbPath, required String sourceId});

  Future<void> crateApiSaveReplaceRule(
      {required String dbPath, required String ruleJson});

  Future<void> crateApiDeleteReplaceRule(
      {required String dbPath, required String id});

  Future<void> crateApiSetReplaceRuleEnabled(
      {required String dbPath, required String id, required bool enabled});

  Future<void> crateApiDeleteSourcesBatch(
      {required String dbPath, required String idsJson});

  Future<String> crateApiGetExploreEntries(
      {required String dbPath, required String sourceId});

  Future<String> crateApiExplore(
      {required String dbPath,
      required String sourceId,
      required String exploreUrl,
      required int page});

  Future<String> crateApiApplyReplaceRules(
      {required String dbPath,
      required String content,
      required PlatformInt64 cacheGeneration,
      String? bookName,
      String? bookOrigin,
      bool applyToTitle = false});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAddBookmark(
      {required String dbPath,
      required String bookId,
      required int chapterIndex,
      required int paragraphIndex,
      String? content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookId, serializer);
        sse_encode_i_32(chapterIndex, serializer);
        sse_encode_i_32(paragraphIndex, serializer);
        sse_encode_opt_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddBookmarkConstMeta,
      argValues: [dbPath, bookId, chapterIndex, paragraphIndex, content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddBookmarkConstMeta => const TaskConstMeta(
        debugName: "add_bookmark",
        argNames: [
          "dbPath",
          "bookId",
          "chapterIndex",
          "paragraphIndex",
          "content"
        ],
      );

  @override
  Future<void> crateApiBatchCreateDownloadChapters(
      {required String dbPath, required String chaptersJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(chaptersJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBatchCreateDownloadChaptersConstMeta,
      argValues: [dbPath, chaptersJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBatchCreateDownloadChaptersConstMeta =>
      const TaskConstMeta(
        debugName: "batch_create_download_chapters",
        argNames: ["dbPath", "chaptersJson"],
      );

  @override
  Future<String> crateApiCreateDownloadTask(
      {required String dbPath, required String taskJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(taskJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateDownloadTaskConstMeta,
      argValues: [dbPath, taskJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateDownloadTaskConstMeta => const TaskConstMeta(
        debugName: "create_download_task",
        argNames: ["dbPath", "taskJson"],
      );

  @override
  Future<String> crateApiCreateDownloadTaskWithChapters(
      {required String dbPath,
      required String taskJson,
      required String chaptersJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(taskJson, serializer);
        sse_encode_String(chaptersJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateDownloadTaskWithChaptersConstMeta,
      argValues: [dbPath, taskJson, chaptersJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateDownloadTaskWithChaptersConstMeta =>
      const TaskConstMeta(
        debugName: "create_download_task_with_chapters",
        argNames: ["dbPath", "taskJson", "chaptersJson"],
      );

  @override
  Future<String> crateApiCreateSource(
      {required String dbPath, required String name, required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateSourceConstMeta,
      argValues: [dbPath, name, url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateSourceConstMeta => const TaskConstMeta(
        debugName: "create_source",
        argNames: ["dbPath", "name", "url"],
      );

  @override
  Future<void> crateApiDeleteBook(
      {required String dbPath, required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteBookConstMeta,
      argValues: [dbPath, id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteBookConstMeta => const TaskConstMeta(
        debugName: "delete_book",
        argNames: ["dbPath", "id"],
      );

  @override
  Future<void> crateApiDeleteBookmark(
      {required String dbPath, required String bookmarkId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookmarkId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteBookmarkConstMeta,
      argValues: [dbPath, bookmarkId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteBookmarkConstMeta => const TaskConstMeta(
        debugName: "delete_bookmark",
        argNames: ["dbPath", "bookmarkId"],
      );

  @override
  Future<void> crateApiDeleteChapter(
      {required String dbPath, required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteChapterConstMeta,
      argValues: [dbPath, id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteChapterConstMeta => const TaskConstMeta(
        debugName: "delete_chapter",
        argNames: ["dbPath", "id"],
      );

  @override
  Future<void> crateApiDeleteDownloadTask(
      {required String dbPath, required String taskId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(taskId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteDownloadTaskConstMeta,
      argValues: [dbPath, taskId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteDownloadTaskConstMeta => const TaskConstMeta(
        debugName: "delete_download_task",
        argNames: ["dbPath", "taskId"],
      );

  @override
  Future<void> crateApiDeleteSource(
      {required String dbPath, required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteSourceConstMeta,
      argValues: [dbPath, id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteSourceConstMeta => const TaskConstMeta(
        debugName: "delete_source",
        argNames: ["dbPath", "id"],
      );

  @override
  Future<String> crateApiDownloadAndSaveChapter(
      {required String dbPath,
      required String taskId,
      required String downloadChapterId,
      required String sourceJson,
      required String chapterUrl,
      required String downloadDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_String(downloadChapterId, serializer);
        sse_encode_String(sourceJson, serializer);
        sse_encode_String(chapterUrl, serializer);
        sse_encode_String(downloadDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDownloadAndSaveChapterConstMeta,
      argValues: [
        dbPath,
        taskId,
        downloadChapterId,
        sourceJson,
        chapterUrl,
        downloadDir
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDownloadAndSaveChapterConstMeta =>
      const TaskConstMeta(
        debugName: "download_and_save_chapter",
        argNames: [
          "dbPath",
          "taskId",
          "downloadChapterId",
          "sourceJson",
          "chapterUrl",
          "downloadDir"
        ],
      );

  @override
  Future<String> crateApiGetAllBooks({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetAllBooksConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAllBooksConstMeta => const TaskConstMeta(
        debugName: "get_all_books",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiGetAllSources({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetAllSourcesConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAllSourcesConstMeta => const TaskConstMeta(
        debugName: "get_all_sources",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiGetBookChapters(
      {required String dbPath, required String bookId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetBookChaptersConstMeta,
      argValues: [dbPath, bookId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetBookChaptersConstMeta => const TaskConstMeta(
        debugName: "get_book_chapters",
        argNames: ["dbPath", "bookId"],
      );

  @override
  Future<String> crateApiGetBookInfoOnline(
      {required String sourceJson, required String bookUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sourceJson, serializer);
        sse_encode_String(bookUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetBookInfoOnlineConstMeta,
      argValues: [sourceJson, bookUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetBookInfoOnlineConstMeta => const TaskConstMeta(
        debugName: "get_book_info_online",
        argNames: ["sourceJson", "bookUrl"],
      );

  @override
  Future<String> crateApiGetBookmarks(
      {required String dbPath, required String bookId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetBookmarksConstMeta,
      argValues: [dbPath, bookId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetBookmarksConstMeta => const TaskConstMeta(
        debugName: "get_bookmarks",
        argNames: ["dbPath", "bookId"],
      );

  @override
  Future<String> crateApiGetChapterContentOnline(
      {required String sourceJson, required String chapterUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sourceJson, serializer);
        sse_encode_String(chapterUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetChapterContentOnlineConstMeta,
      argValues: [sourceJson, chapterUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetChapterContentOnlineConstMeta =>
      const TaskConstMeta(
        debugName: "get_chapter_content_online",
        argNames: ["sourceJson", "chapterUrl"],
      );

  @override
  Future<String> crateApiGetChapterContentWithSourceFromDb(
      {required String dbPath,
      required String sourceId,
      required String chapterUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(sourceId, serializer);
        sse_encode_String(chapterUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetChapterContentWithSourceFromDbConstMeta,
      argValues: [dbPath, sourceId, chapterUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetChapterContentWithSourceFromDbConstMeta =>
      const TaskConstMeta(
        debugName: "get_chapter_content_with_source_from_db",
        argNames: ["dbPath", "sourceId", "chapterUrl"],
      );

  @override
  Future<String> crateApiGetChapterListOnline(
      {required String sourceJson, required String bookUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sourceJson, serializer);
        sse_encode_String(bookUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetChapterListOnlineConstMeta,
      argValues: [sourceJson, bookUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetChapterListOnlineConstMeta =>
      const TaskConstMeta(
        debugName: "get_chapter_list_online",
        argNames: ["sourceJson", "bookUrl"],
      );

  @override
  Future<int> crateApiGetDbVersion({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetDbVersionConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDbVersionConstMeta => const TaskConstMeta(
        debugName: "get_db_version",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiGetDownloadChapters(
      {required String dbPath, required String taskId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(taskId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetDownloadChaptersConstMeta,
      argValues: [dbPath, taskId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDownloadChaptersConstMeta =>
      const TaskConstMeta(
        debugName: "get_download_chapters",
        argNames: ["dbPath", "taskId"],
      );

  @override
  Future<String> crateApiGetDownloadTaskByBook(
      {required String dbPath, required String bookId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetDownloadTaskByBookConstMeta,
      argValues: [dbPath, bookId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDownloadTaskByBookConstMeta =>
      const TaskConstMeta(
        debugName: "get_download_task_by_book",
        argNames: ["dbPath", "bookId"],
      );

  @override
  Future<String> crateApiGetDownloadTasks({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetDownloadTasksConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDownloadTasksConstMeta => const TaskConstMeta(
        debugName: "get_download_tasks",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiGetEnabledSources({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetEnabledSourcesConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetEnabledSourcesConstMeta => const TaskConstMeta(
        debugName: "get_enabled_sources",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiGetReadingProgress(
      {required String dbPath, required String bookId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetReadingProgressConstMeta,
      argValues: [dbPath, bookId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetReadingProgressConstMeta => const TaskConstMeta(
        debugName: "get_reading_progress",
        argNames: ["dbPath", "bookId"],
      );

  @override
  Future<String> crateApiGetSourceForDownload(
      {required String dbPath, required String sourceId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(sourceId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetSourceForDownloadConstMeta,
      argValues: [dbPath, sourceId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetSourceForDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "get_source_for_download",
        argNames: ["dbPath", "sourceId"],
      );

  @override
  Future<int> crateApiImportSourcesFromJson(
      {required String dbPath, required String json}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(json, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiImportSourcesFromJsonConstMeta,
      argValues: [dbPath, json],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImportSourcesFromJsonConstMeta =>
      const TaskConstMeta(
        debugName: "import_sources_from_json",
        argNames: ["dbPath", "json"],
      );

  @override
  Future<String> crateApiInitLegado({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInitLegadoConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitLegadoConstMeta => const TaskConstMeta(
        debugName: "init_legado",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiPing() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPingConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPingConstMeta => const TaskConstMeta(
        debugName: "ping",
        argNames: [],
      );

  @override
  Future<void> crateApiReplaceBookChapters(
      {required String dbPath,
      required String bookId,
      required String chaptersJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookId, serializer);
        sse_encode_String(chaptersJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 50, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiReplaceBookChaptersConstMeta,
      argValues: [dbPath, bookId, chaptersJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReplaceBookChaptersConstMeta =>
      const TaskConstMeta(
        debugName: "replace_book_chapters",
        argNames: ["dbPath", "bookId", "chaptersJson"],
      );

  @override
  Future<void> crateApiReplaceBookChaptersPreservingContent(
      {required String dbPath,
      required String bookId,
      required String chaptersJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookId, serializer);
        sse_encode_String(chaptersJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 49, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiReplaceBookChaptersPreservingContentConstMeta,
      argValues: [dbPath, bookId, chaptersJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReplaceBookChaptersPreservingContentConstMeta =>
      const TaskConstMeta(
        debugName: "replace_book_chapters_preserving_content",
        argNames: ["dbPath", "bookId", "chaptersJson"],
      );

  @override
  Future<void> crateApiSaveBook(
      {required String dbPath, required String bookJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSaveBookConstMeta,
      argValues: [dbPath, bookJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSaveBookConstMeta => const TaskConstMeta(
        debugName: "save_book",
        argNames: ["dbPath", "bookJson"],
      );

  @override
  Future<void> crateApiSaveChapter(
      {required String dbPath, required String chapterJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(chapterJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSaveChapterConstMeta,
      argValues: [dbPath, chapterJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSaveChapterConstMeta => const TaskConstMeta(
        debugName: "save_chapter",
        argNames: ["dbPath", "chapterJson"],
      );

  @override
  Future<void> crateApiSaveReadingProgress(
      {required String dbPath,
      required String bookId,
      required int chapterIndex,
      required int paragraphIndex,
      required int offset}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(bookId, serializer);
        sse_encode_i_32(chapterIndex, serializer);
        sse_encode_i_32(paragraphIndex, serializer);
        sse_encode_i_32(offset, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSaveReadingProgressConstMeta,
      argValues: [dbPath, bookId, chapterIndex, paragraphIndex, offset],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSaveReadingProgressConstMeta =>
      const TaskConstMeta(
        debugName: "save_reading_progress",
        argNames: [
          "dbPath",
          "bookId",
          "chapterIndex",
          "paragraphIndex",
          "offset"
        ],
      );

  @override
  Future<void> crateApiSaveSource(
      {required String dbPath, required String sourceJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(sourceJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSaveSourceConstMeta,
      argValues: [dbPath, sourceJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSaveSourceConstMeta => const TaskConstMeta(
        debugName: "save_source",
        argNames: ["dbPath", "sourceJson"],
      );

  @override
  Future<String> crateApiSearchBooksOffline(
      {required String dbPath, required String keyword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(keyword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSearchBooksOfflineConstMeta,
      argValues: [dbPath, keyword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchBooksOfflineConstMeta => const TaskConstMeta(
        debugName: "search_books_offline",
        argNames: ["dbPath", "keyword"],
      );

  @override
  Future<String> crateApiSearchBooksOnline(
      {required String sourceJson, required String keyword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sourceJson, serializer);
        sse_encode_String(keyword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSearchBooksOnlineConstMeta,
      argValues: [sourceJson, keyword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchBooksOnlineConstMeta => const TaskConstMeta(
        debugName: "search_books_online",
        argNames: ["sourceJson", "keyword"],
      );

  @override
  Future<String> crateApiSearchWithSourceFromDb(
      {required String dbPath,
      required String sourceId,
      required String keyword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(sourceId, serializer);
        sse_encode_String(keyword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 36, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSearchWithSourceFromDbConstMeta,
      argValues: [dbPath, sourceId, keyword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchWithSourceFromDbConstMeta =>
      const TaskConstMeta(
        debugName: "search_with_source_from_db",
        argNames: ["dbPath", "sourceId", "keyword"],
      );

  @override
  Future<String> crateApiSearchWithSourceFromDbV2(
      {required String dbPath,
      required String sourceId,
      required String keyword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(sourceId, serializer);
        sse_encode_String(keyword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 52, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSearchWithSourceFromDbV2ConstMeta,
      argValues: [dbPath, sourceId, keyword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchWithSourceFromDbV2ConstMeta =>
      const TaskConstMeta(
        debugName: "search_with_source_from_db_v2",
        argNames: ["dbPath", "sourceId", "keyword"],
      );

  @override
  Future<void> crateApiSetSourceEnabled(
      {required String dbPath, required String id, required bool enabled}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(id, serializer);
        sse_encode_bool(enabled, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 37, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSetSourceEnabledConstMeta,
      argValues: [dbPath, id, enabled],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetSourceEnabledConstMeta => const TaskConstMeta(
        debugName: "set_source_enabled",
        argNames: ["dbPath", "id", "enabled"],
      );

  @override
  Future<void> crateApiUpdateChapterContent(
      {required String dbPath,
      required String chapterId,
      required String content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(chapterId, serializer);
        sse_encode_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 38, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiUpdateChapterContentConstMeta,
      argValues: [dbPath, chapterId, content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpdateChapterContentConstMeta =>
      const TaskConstMeta(
        debugName: "update_chapter_content",
        argNames: ["dbPath", "chapterId", "content"],
      );

  @override
  Future<void> crateApiUpdateDownloadChapterStatus(
      {required String dbPath,
      required String chapterId,
      required int status,
      String? filePath,
      required PlatformInt64 fileSize,
      String? errorMessage}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(chapterId, serializer);
        sse_encode_i_32(status, serializer);
        sse_encode_opt_String(filePath, serializer);
        sse_encode_i_64(fileSize, serializer);
        sse_encode_opt_String(errorMessage, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 39, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiUpdateDownloadChapterStatusConstMeta,
      argValues: [dbPath, chapterId, status, filePath, fileSize, errorMessage],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpdateDownloadChapterStatusConstMeta =>
      const TaskConstMeta(
        debugName: "update_download_chapter_status",
        argNames: [
          "dbPath",
          "chapterId",
          "status",
          "filePath",
          "fileSize",
          "errorMessage"
        ],
      );

  @override
  Future<void> crateApiUpdateDownloadProgress(
      {required String dbPath,
      required String taskId,
      required int downloadedChapters,
      required PlatformInt64 downloadedSize}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_i_32(downloadedChapters, serializer);
        sse_encode_i_64(downloadedSize, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 40, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiUpdateDownloadProgressConstMeta,
      argValues: [dbPath, taskId, downloadedChapters, downloadedSize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpdateDownloadProgressConstMeta =>
      const TaskConstMeta(
        debugName: "update_download_progress",
        argNames: ["dbPath", "taskId", "downloadedChapters", "downloadedSize"],
      );

  @override
  Future<void> crateApiUpdateDownloadTaskStatus(
      {required String dbPath,
      required String taskId,
      required int status,
      String? errorMessage}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_i_32(status, serializer);
        sse_encode_opt_String(errorMessage, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 41, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiUpdateDownloadTaskStatusConstMeta,
      argValues: [dbPath, taskId, status, errorMessage],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpdateDownloadTaskStatusConstMeta =>
      const TaskConstMeta(
        debugName: "update_download_task_status",
        argNames: ["dbPath", "taskId", "status", "errorMessage"],
      );

  @override
  Future<String> crateApiValidateSourceRules({required String sourceJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sourceJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 42, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiValidateSourceRulesConstMeta,
      argValues: [sourceJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiValidateSourceRulesConstMeta =>
      const TaskConstMeta(
        debugName: "validate_source_rules",
        argNames: ["sourceJson"],
      );

  @override
  Future<String> crateApiValidateSourceFromDb(
      {required String dbPath, required String sourceId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(sourceId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 43, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiValidateSourceFromDbConstMeta,
      argValues: [dbPath, sourceId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiValidateSourceFromDbConstMeta =>
      const TaskConstMeta(
        debugName: "validate_source_from_db",
        argNames: ["dbPath", "sourceId"],
      );

  @override
  Future<String> crateApiExportAllSources({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 44, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExportAllSourcesConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportAllSourcesConstMeta => const TaskConstMeta(
        debugName: "export_all_sources",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiGetReplaceRules({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 45, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetReplaceRulesConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }
  TaskConstMeta get kCrateApiGetReplaceRulesConstMeta =>
      const TaskConstMeta(
        debugName: "get_replace_rules",
        argNames: ["dbPath"],
      );

  @override
  Future<String> crateApiGetSourceRuleSearchRaw(
      {required String dbPath, required String sourceId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(sourceId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 51, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetSourceRuleSearchRawConstMeta,
      argValues: [dbPath, sourceId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetSourceRuleSearchRawConstMeta =>
      const TaskConstMeta(
        debugName: "get_source_rule_search_raw",
        argNames: ["dbPath", "sourceId"],
      );

  @override
  Future<void> crateApiSaveReplaceRule(
      {required String dbPath, required String ruleJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(ruleJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 46, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSaveReplaceRuleConstMeta,
      argValues: [dbPath, ruleJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSaveReplaceRuleConstMeta => const TaskConstMeta(
        debugName: "save_replace_rule",
        argNames: ["dbPath", "ruleJson"],
      );

  @override
  Future<void> crateApiDeleteReplaceRule(
      {required String dbPath, required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 47, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteReplaceRuleConstMeta,
      argValues: [dbPath, id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteReplaceRuleConstMeta => const TaskConstMeta(
        debugName: "delete_replace_rule",
        argNames: ["dbPath", "id"],
      );

  @override
  Future<void> crateApiSetReplaceRuleEnabled(
      {required String dbPath, required String id, required bool enabled}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(id, serializer);
        sse_encode_bool(enabled, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 48, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSetReplaceRuleEnabledConstMeta,
      argValues: [dbPath, id, enabled],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetReplaceRuleEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_replace_rule_enabled",
        argNames: ["dbPath", "id", "enabled"],
      );

  @override
  Future<void> crateApiDeleteSourcesBatch(
      {required String dbPath, required String idsJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(idsJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 54, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteSourcesBatchConstMeta,
      argValues: [dbPath, idsJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteSourcesBatchConstMeta => const TaskConstMeta(
        debugName: "delete_sources_batch",
        argNames: ["dbPath", "idsJson"],
      );

  @override
  Future<String> crateApiGetExploreEntries(
      {required String dbPath, required String sourceId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(sourceId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 55, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetExploreEntriesConstMeta,
      argValues: [dbPath, sourceId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetExploreEntriesConstMeta => const TaskConstMeta(
        debugName: "get_explore_entries",
        argNames: ["dbPath", "sourceId"],
      );

  @override
  Future<String> crateApiExplore(
      {required String dbPath,
      required String sourceId,
      required String exploreUrl,
      required int page}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(sourceId, serializer);
        sse_encode_String(exploreUrl, serializer);
        sse_encode_i_32(page, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 56, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiExploreConstMeta,
      argValues: [dbPath, sourceId, exploreUrl, page],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExploreConstMeta => const TaskConstMeta(
        debugName: "explore",
        argNames: ["dbPath", "sourceId", "exploreUrl", "page"],
      );

  @override
  Future<String> crateApiApplyReplaceRules(
      {required String dbPath,
      required String content,
      required PlatformInt64 cacheGeneration,
      String? bookName,
      String? bookOrigin,
      bool applyToTitle = false}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(content, serializer);
        sse_encode_i_64(cacheGeneration, serializer);
        // R24: 3 new params for scope filtering. Manual patch — must
        // be re-applied after flutter_rust_bridge_codegen run.
        sse_encode_opt_String(bookName, serializer);
        sse_encode_opt_String(bookOrigin, serializer);
        sse_encode_bool(applyToTitle, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 57, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiApplyReplaceRulesConstMeta,
      argValues: [
        dbPath,
        content,
        cacheGeneration,
        bookName,
        bookOrigin,
        applyToTitle,
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApplyReplaceRulesConstMeta => const TaskConstMeta(
        debugName: "apply_replace_rules",
        argNames: [
          "dbPath",
          "content",
          "cacheGeneration",
          "bookName",
          "bookOrigin",
          "applyToTitle",
        ],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
